#%RAML 1.0
title: mt-mysql-sapi
description : System API conecting to MySQL Database

uses:
  commonHeaders: mt-common-header-library.raml
traits:
  commonErrors: !include mt-common-error-responses.raml

types:
  User: !include Datatypes/GetUser.raml
  Subscription: !include Datatypes/postsub.raml
  Alerts: !include Datatypes/alerts.raml
  Health: !include Datatypes/health.raml
  Email: !include Datatypes/Email.raml
  saleforce: !include Datatypes/salesforce.raml

/users:
  is: [commonHeaders.client-id-required, commonHeaders.correlationId, commonErrors]
  post:
    displayName: New User
    description: Add new user to database
    body:
      application/json:
        type: User
        example: !include Example/postuser.raml
    responses:
      200:
        body:
          application/json:
            example:
              message: "User Added to Database"
  get:
      displayName: Get all users
      description: Show details of all users
      responses:
        200:
          body:
            application/json:
              type: User[]
              example: !include Example/Getusers.raml

  /{userid}:
      get:
        displayName: Get single user
        description: Fetch information on single user
        responses:
          200:
            body:
              application/json:
                type: User
                example: !include Example/getuserbyid.raml
      /subscription:
        post:
          displayName: Add subscription details
          description:  Add subscription details of the  user
          body:
            application/json:
              type: Subscription
              example: !include Example/postsub.raml
          responses:
                200:
                      body:
                            application/json:
                                  example:
                                        message: "Subscription Added Successfully"    
        get:
          displayName: Get Subscription Info
          description: Get all the Subscriptions
          queryParameters:
            from_time:
              type: time-only
              example: 18:00:00
              required: false
            to_time:
              type: time-only
              example: 18:00:00
              required: false

          responses:
            200:
              body:
                application/json:
                  type: Subscription[]
                  example: !include Example/getsub.raml

        /{subscriptionid}:
          get:
            displayName: Get Subscription by ID
            description: Get single subscription info
            responses:
              200:
                body:
                  application/json:
                    type: Subscription
                    example: !include Example/getsubbyid.raml
          /alerts:
            post:
              displayName: Post alert details 
              description:  Post the alert details to DB
              body:
                application/json:
                  type: Alerts
                  example: !include Example/postalerts.raml
              responses:
                      200:
                        body:
                          application/json:
                              example:
                                  message: "Alert Generated"      
            get:
              displayName: Get all alerts  
              description: Get all alerts for a particular subscription
              responses:
                200:
                  body:
                    application/json:
                      type: Alerts[]
                      example: !include Example/alerts.raml

            /{alertid}:
              
              get:
                displayName: Get Single alert 
                description: Get Details for Single alert of a subscription
                responses:
                  200:
                    body:
                      application/json:
                        type: Alerts
                        example: !include Example/alertbyid.raml
/health:
  is: [commonErrors]
  get:
    displayName: Health information
    description: fetch information about api Health
    responses:
      200:
        body:
          application/json:
            type: Health
            example: !include Example/health.raml  
/subscriptionbytime:
    is: [commonErrors]
    get:
      displayName: Get all subscriptions
      description: Get all details of subscriptions of all users
      queryParameters:
            from_time:
              type: time-only
              example: 18:00:00
              required: false
            to_time:
              type: time-only
              example: 18:00:00
              required: false
      responses:
            200:
              body:
                application/json:
                  type: Subscription[]
                  example: !include Example/getsub.raml           
/update:
  is: [commonErrors]
  put:
    displayName: Update Sql
    description: Update Notification Status
    responses:
      200:
        body:
          application/json:
            example:
              Message : "Updated Successfully"
/alertgeneration:
  is: [commonErrors]
  get:
    displayName: Alert Generation
    description: Fetch stored Alerts for sending Email
    responses:
      200:
        body:
          application/json:
            type: Email
            example: !include Example/Email.raml
/salesforce:
  is: [commonHeaders.client-id-required, commonHeaders.correlationId, commonErrors]
  get:
    displayName: Subscribed User Data
    description: Fetch Detailed information of subscribed Users
    responses:
      200:
        body:
          application/json:
            type: saleforce[]
            example: !include Example/salesforce.raml  

              
                                           













