import httpx

API_INSTANCE_URL = "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/{org_id}/environments/{env_id}/apis"
CREATE_APP_URL = "https://anypoint.mulesoft.com/exchange/api/v2/organizations/{org_id}/applications?apiInstanceId={api_id}"
LIST_APIS_URL = "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/{org_id}/environments/{env_id}/apis"
CREATE_CONTRACT_URL = "https://anypoint.mulesoft.com/exchange/api/v2/organizations/{org_id}/applications/{app_id}/contracts"


#Create API INSTANCE
def register(mcp):
    @mcp.tool()
    async def create_api_instance(
        token: str,
        org_id: str,
        env_id: str,
        asset_id: str,
        version: str,
        instance_label: str = None
    ) -> str:
        """
        Create an API Instance in API Manager for a published Exchange asset.
        """

        if instance_label is None:
            instance_label = asset_id

        url = API_INSTANCE_URL.format(org_id=org_id, env_id=env_id)

        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }

        payload = {
            "instanceLabel": instance_label,
            "spec": {
                "groupId": org_id,
                "assetId": asset_id,
                "version": version
            },
            "endpoint": {
                "uri": "https://anypoint.mulesoft.com/api/v1/",
                "proxyUri": "http://0.0.0.0:8081/",
                "isCloudHub": True
            },
            "technology": "mule4"
        }

        async with httpx.AsyncClient() as client:
            try:
                resp = await client.post(
                    url,
                    headers=headers,
                    json=payload,
                    timeout=40.0
                )
                resp.raise_for_status()
                return resp.text
            except Exception as e:
                return f"Error creating API instance: {e}"


    #LIST API INTSANCES
    @mcp.tool()
    async def list_api_instances(
        token: str,
        org_id: str,
        env_id: str
    ) -> dict:
        """
        List all API instances in an environment.
        Equivalent to instanceList in the Node.js automation.
        """

        url = LIST_APIS_URL.format(org_id=org_id, env_id=env_id)

        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }

        async with httpx.AsyncClient() as client:
            try:
                resp = await client.get(url, headers=headers, timeout=40.0)
                resp.raise_for_status()
                return resp.json()   # contains assets[], apis[], ids, etc.
            except Exception as e:
                return {"error": str(e)}


    #Create Application 
    @mcp.tool()
    async def create_application(
        token: str,
        org_id: str,
        api_id: str,
        app_name: str = "auto-generated-app"
    ) -> dict:
        """
        Create an Application in Anypoint Platform to obtain clientId and clientSecret.
        This is equivalent to requestAccessApi in the Node.js automation.
        """

        url = CREATE_APP_URL.format(org_id=org_id, api_id=api_id)

        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }

        payload = {
            "name": app_name,
            "description": "Application generated by MCP Server",
            "url": "http://example.com",
            "redirectUri": ["http://localhost/callback"],
            "grantTypes": [],
            "apiEndpoints": False
        }

        async with httpx.AsyncClient() as client:
            try:
                resp = await client.post(
                    url,
                    headers=headers,
                    json=payload,
                    timeout=40.0
                )
                resp.raise_for_status()
                return resp.json()
            except Exception as e:
                return {
                    "error": str(e)
                }

    #CREATE API CONTRACT
    @mcp.tool()
    async def create_api_contract(
        token: str,
        org_id: str,
        app_id: str,
        api_id: str,
        asset_id: str,
        version: str
    ) -> dict:
        """
        Create API contract for an existing Application on an API Instance.
        """

        url = CREATE_CONTRACT_URL.format(org_id=org_id, app_id=app_id)

        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }

        payload = {
            "apiId": api_id,
            "instanceType": "api",
            "acceptedTerms": True,
            "organizationId": org_id,
            "groupId": org_id,
            "assetId": asset_id,
            "version": version,
            "versionGroup": "v1"
        }

        async with httpx.AsyncClient() as client:
            try:
                resp = await client.post(url, headers=headers, json=payload, timeout=40.0)
                resp.raise_for_status()
                return resp.json()
            except Exception as e:
                return {"error": str(e)}